apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    hpa: my-temp-hpa
  name: my-temp-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-temp
  targetCPUUtilizationPercentage: 20